name: Sync Static Files

on:
  push:
    paths:
      - 'static/**'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files in static directory
        id: changed-files
        run: |
          # Define the directory to check
          DIR_TO_CHECK="static/**"
          
          # Get changed files using git
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- $DIR_TO_CHECK || git diff --name-only HEAD~1 HEAD -- $DIR_TO_CHECK)
          
          # Check if there are any changed files
          if [[ -n "$CHANGED_FILES" ]]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in $DIR_TO_CHECK directory"
            echo "$CHANGED_FILES"
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in $DIR_TO_CHECK directory"
          fi

      - name: Install SSH key
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Sync files if changes detected
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
            rsync -avz --delete ./static/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}/static/

      - name: Restart executables
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_path: .github/workflows/restart.sh